services:
  app:
    build:
      context: ./docker
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        NODE_MAJOR: 18
        APP_BUILT_ENV: 'prod'
    container_name: torque_app
    hostname: torque_app
    env_file:
      - .env
    ports:
      - 3000:80
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html/
#      - ./index.php:/usr/share/nginx/html/index.php
#      - ./composer.json:/usr/share/nginx/html/composer.json
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
